# Generated by Django 3.2.9 on 2021-11-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
